# Generated using regular expressions search & replace on data pasted from NSLS2MotorStatusREcords.ods 
#
# Search for: (.*)\t(.*)
# Replace with: sed -i 's/\2/\1/g' inFile
#
sed -i 's/$(DEVICE):$(MRN)_CALC1_AXIS_STS/$(SYS){$(DEV)}-CALC1-Axis-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_CALC2_AXIS_STS/$(SYS){$(DEV)}-CALC2-Axis-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_AXIS_STS/$(SYS){$(DEV)}-Axis-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_MTACT_STS/$(SYS){$(DEV)}-MTACT-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_NENDL_STS/$(SYS){$(DEV)}-NENDL-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_PENDL_STS/$(SYS){$(DEV)}-PENDL-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_ESAEN_STS/$(SYS){$(DEV)}-ESAEN-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_AMPEN_STS/$(SYS){$(DEV)}-AMPEN-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_TIACT_STS/$(SYS){$(DEV)}-TIACT-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_INTMO_STS/$(SYS){$(DEV)}-INTMO-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_DWPRO_STS/$(SYS){$(DEV)}-DWPRO-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_DAERR_STS/$(SYS){$(DEV)}-DAERR-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_DVZER_STS/$(SYS){$(DEV)}-DVZER-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_ABDEC_STS/$(SYS){$(DEV)}-ABDEC-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_BLREQ_STS/$(SYS){$(DEV)}-BLREQ-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_HSRCH_STS/$(SYS){$(DEV)}-HSRCH-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_UWPEN_STS/$(SYS){$(DEV)}-UWPEN-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_UWSEN_STS/$(SYS){$(DEV)}-UWSEN-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_ASODE_STS/$(SYS){$(DEV)}-ASODE-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_PHMTR_STS/$(SYS){$(DEV)}-PHMTR-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_FOFFM_STS/$(SYS){$(DEV)}-FOFFM-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_FOLLE_STS/$(SYS){$(DEV)}-FOLLE-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_ERRTG_STS/$(SYS){$(DEV)}-ERRTG-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_SWPOC_STS/$(SYS){$(DEV)}-SWPOC-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_ACOMO_STS/$(SYS){$(DEV)}-ACOMO-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_MAXRS_STS/$(SYS){$(DEV)}-MAXRS-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_CSCA_/$(SYS){$(DEV)}-CSCA-/g' inFile
sed -i 's/$(DEVICE):$(MRN)_CSNUM_/$(SYS){$(DEV)}-CSNUM-/g' inFile
sed -i 's/$(DEVICE):$(MRN)_AXCAL_/$(SYS){$(DEV)}-AXCAL-/g' inFile
sed -i 's/$(DEVICE):$(MRN)_AXDF_/$(SYS){$(DEV)}-AXDF-/g' inFile
sed -i 's/$(DEVICE):$(MRN)_CS0_/$(SYS){$(DEV)}-CS0-/g' inFile
sed -i 's/$(DEVICE):$(MRN)_CS1_/$(SYS){$(DEV)}-CS1-/g' inFile
sed -i 's/$(DEVICE):$(MRN)_CS2_/$(SYS){$(DEV)}-CS2-/g' inFile
sed -i 's/$(DEVICE):$(MRN)_CS3_/$(SYS){$(DEV)}-CS3-/g' inFile
sed -i 's/$(DEVICE):$(MRN)_ASSCS_STS/$(SYS){$(DEV)}-ASSCS-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_SPARE_STS/$(SYS){$(DEV)}-SPARE-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_FRPOS_STS/$(SYS){$(DEV)}-FRPOS-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_AX3_/$(SYS){$(DEV)}-AX3-/g' inFile
sed -i 's/$(DEVICE):$(MRN)_AX2_/$(SYS){$(DEV)}-AX2-/g' inFile
sed -i 's/$(DEVICE):$(MRN)_AX1_/$(SYS){$(DEV)}-AX1-/g' inFile
sed -i 's/$(DEVICE):$(MRN)_AX0_/$(SYS){$(DEV)}-AX0-/g' inFile
sed -i 's/$(DEVICE):$(MRN)_SOPL_STS/$(SYS){$(DEV)}-SOPL-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_SODPL_STS/$(SYS){$(DEV)}-SODPL-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_PHSRA_STS/$(SYS){$(DEV)}-PHSRA-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_PREFE_STS/$(SYS){$(DEV)}-PREFE-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_TRMOV_STS/$(SYS){$(DEV)}-TRMOV-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_IFFE_STS/$(SYS){$(DEV)}-IFFE-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_AMFAE_STS/$(SYS){$(DEV)}-AMFAE-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_BADIF_STS/$(SYS){$(DEV)}-BADIF-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_AMFE_STS/$(SYS){$(DEV)}-AMFE-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_FAFOE_STS/$(SYS){$(DEV)}-FAFOE-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_WFOER_STS/$(SYS){$(DEV)}-WFOER-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_INVAMP_STS/$(SYS){$(DEV)}-INVAMP-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_INVMTACT_STS/$(SYS){$(DEV)}-INVMTACT-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_INPOS_STS/$(SYS){$(DEV)}-INPOS-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_ERROR1_STS/$(SYS){$(DEV)}-ERROR1-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_ERROR2_STS/$(SYS){$(DEV)}-ERROR2-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_LOOPM_STS/$(SYS){$(DEV)}-LOOPM-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_ALOOPM_STS/$(SYS){$(DEV)}-ALOOPM-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_STS_CMD/$(SYS){$(DEV)}-STS-Cmd/g' inFile
sed -i 's/$(DEVICE):$(MRN)_STSW1_STS/$(SYS){$(DEV)}-STSW1-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_STSW2_STS/$(SYS){$(DEV)}-STSW2-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_STSW1B_STS/$(SYS){$(DEV)}-STSW1B-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_STSW2B_STS/$(SYS){$(DEV)}-STSW2B-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_STSW2A_STS/$(SYS){$(DEV)}-STSW2A-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_STSW1A_STS/$(SYS){$(DEV)}-STSW1A-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_CMDFAN_/$(SYS){$(DEV)}-CmdFAN-/g' inFile
sed -i 's/$(DEVICE):$(MRN)_PMACERROR_STS/$(SYS){$(DEV)}-PMACERROR-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_RAW_POSITION_MON/$(SYS){$(DEV)}-RAW-POSITION-Mon/g' inFile
sed -i 's/$(DEVICE):$(MRN)_STALL_/$(SYS){$(DEV)}-STALL-/g' inFile
sed -i 's/$(DEVICE):$(MRN)_STALL_STS/$(SYS){$(DEV)}-STALL-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_FOLER_CMD/$(SYS){$(DEV)}-FOLER-Cmd/g' inFile
sed -i 's/$(DEVICE):$(MRN)_FOLER_MON/$(SYS){$(DEV)}-FOLER-Mon/g' inFile
sed -i 's/$(DEVICE):$(MRN)_ACVES_CMD/$(SYS){$(DEV)}-ACVES-Cmd/g' inFile
sed -i 's/$(DEVICE):$(MRN)_ACVES_MON/$(SYS){$(DEV)}-ACVES-Mon/g' inFile
sed -i 's/$(DEVICE):$(MRN)_CMDFAN2_/$(SYS){$(DEV)}-CmdFAN2-/g' inFile
sed -i 's/$(DEVICE):$(MRN)_KILL_MOTOR_CMD/$(SYS){$(DEV)}-KILL-MOTOR-Cmd/g' inFile
sed -i 's/$(DEVICE):$(MRN)_ACTIVATE_CMD/$(SYS){$(DEV)}-ACTIVATE-Cmd/g' inFile
sed -i 's/$(DEVICE):$(MRN)_CLOSE_LOOP_CMD/$(SYS){$(DEV)}-CLOSE-LOOP-Cmd/g' inFile
sed -i 's/$(DEVICE):$(MRN)_HOCPL_STS/$(SYS){$(DEV)}-HOCPL-Sts/g' inFile
sed -i 's/$(DEVICE):$(MRN)_I10_/$(SYS){$(DEV)}-I10-/g' inFile
'
